default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: campshare_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: campshare_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: campshare_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>