class Brand < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'Coleman' },
    { id: 3, name: 'タンスのゲン' },
    { id: 4, name: 'LAD WEATHER' },
    { id: 5, name: 'peace park' },
    { id: 6, name: 'AND MYSELF' },
    { id: 7, name: 'MERMONT' },
    { id: 8, name: 'South Light' },
    { id: 9, name: 'snow peak' },
    { id: 10, name: 'CAPTAIN STAG' },
    { id: 11, name: 'CAMPINGMOON' },
    { id: 12, name: 'FIELDOOR' },
    { id: 13, name: 'DOD' },
    { id: 14, name: 'SOTO' },
    { id: 15, name: 'LOGOS' },
    { id: 16, name: '山善' },
    { id: 17, name: 'IRIS OHYAMA' },
    { id: 18, name: 'Hill Stone' },
    { id: 19, name: 'BAREBONES' },
    { id: 20, name: 'UNIFLAME' },
    { id: 21, name: 'JEJアステージ' },
    { id: 22, name: 'Hilander' },
    { id: 23, name: '無印良品' },
    { id: 24, name: 'EENOUR' },
    { id: 25, name: 'DRESS' },
    { id: 26, name: 'DABADA' },
    { id: 27, name: 'コーナン' },
    { id: 28, name: 'WEIMALL' },
    { id: 29, name: 'creer' },
    { id: 30, name: 'WHATNOT' },
    { id: 31, name: 'その他' }
  ]
  end